services:
  okky-jobs-backend:
    build: 
      context: .
      platforms:
        - linux/amd64
    ports:
      - "8002:8002"
    environment:
      - DB_HOST=${DB_HOST:-localhost}
      - DB_USER=${DB_USER:-crawling}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-crawling}
      - DB_PORT=${DB_PORT:-3306}
      - ROOT_PATH=${ROOT_PATH:-/okky}
      - HOST=0.0.0.0
      - PORT=8002
      - RELOAD=false
    volumes:
      - ./logs:/app/logs
      - ./exports:/app/exports
    restart: unless-stopped
    networks:
      - okky-network

  okky-scheduler:
    build: 
      context: .
      platforms:
        - linux/amd64
    command: python -m src.okky_jobs.scheduler.scheduler
    environment:
      - DB_HOST=${DB_HOST:-localhost}
      - DB_USER=${DB_USER:-crawling}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-crawling}
      - DB_PORT=${DB_PORT:-3306}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - okky-network

networks:
  okky-network:
    driver: bridge
